# kafka
kafka.bootstrap.servers=localhost:9092
kafka.topic.social=eth_social_stream
kafka.topic.trade=topic_trade_signals
kafka.group.id=flink-quant-aggregator

mysql.url=jdbc:mysql://localhost:3306/trade?useSSL=false
mysql.user=root
mysql.password=streampark

# milvus-standalone
milvus.host=localhost
milvus.port=19530

# host.docker.internal
ollama.api.url=http://localhost:11434/api/generate
ollama.embedding.url=http://localhost:11434/api/embeddings