# ???????big-data-platform ???????
kafka.bootstrap.servers=kafka-broker:9092
kafka.topic.social=topic_social_stream
kafka.topic.trade=topic_trade_signals
kafka.group.id=flink-quant-aggregator

mysql.url=jdbc:mysql://mysql-db:3306/stock_quant?useSSL=false
mysql.user=quant_user
mysql.password=quant_secret

milvus.host=milvus-standalone
milvus.port=19530

ollama.api.url=http://llama-cpp-server:11434/api/generate
ollama.embedding.url=http://llama-cpp-server:11434/api/embeddings